name: Auto Documentation on Merge

# 조건 : main branch에 PR이 닫히면 실행함
on:
  pull_request:
    types: [closed]
    branches:
      - main

  # 혹은 Actions 탭에서 버튼 클릭으로 실행
  workflow_dispatch:

# 실행 task
jobs:
  generate-docs:
    # PR이 Merge 되었거나, 수동 실행일 때만 진행
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    # 권한 부여
    permissions:
      contents: write

    steps:
      # 코드 가져오기
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # history까지 가져오기 위해 depth : 0으로 설정
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'  # 의존성 캐싱

      # 의존성 설치
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # main 함수 실행 (주석 처리에 따라 docs or readme 업데이트)
      - name: Run AutoDocs
        env:
          # api 키 주입
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        # 조건에 따라 수행
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BASE_SHA=${{ github.event.pull_request.base.sha }}
            HEAD_SHA=${{ github.event.pull_request.head.sha }}
            echo "PR Detected: Diff from $BASE_SHA to $HEAD_SHA"
            python src/main.py --base $BASE_SHA --head $HEAD_SHA
          
          else
            echo "Manual Run: Checking latest commit"
            python src/main.py
          fi

      # 레포에 docs 저장 (변경 사항 있을 때만 commit)
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'Docs Bot'
          git config --global user.email 'bot@noreply.github.com'
          
          git add README.md generated_docs.md || true
          
          if ! git diff --staged --quiet; then
            git commit -m "docs: Update documentation & README automatically"
            git push
          else
            echo "변경 사항 없음"
          fi